types:
  - build

build:
  type: build
  script:
    - go get -u gitlab.com/magan/gobits
    - go get -u gitlab.com/magan/gobits/example
    - go build gitlab.com/magan/gobits/example
  tags:
    - golang